### ISSUE TITLE
text/shaclc(-ent) not in `.getContentTypes()` returned array

### ISSUE THREAD

**Issue by BelgianNoise** [rubensworks/rdf-serialize.js#15]
According to the README `text/shaclc` and `text/shaclc-ext` are supported.

They are however not included in the array returned by `.getContentTypes()`.

### Reproduce

```
  const supportedTypes = await rdfSerializer.getContentTypes();
  console.log('======', supportedTypes);
  if (!supportedTypes.includes('text/shaclc')) throw new Error(`Can't parse turtle to ${contentType}`);
```

Throws and prints

```
====== [
      'application/ld+json',
      'application/n-quads',
      'application/n-triples',
      'application/trig',
      'text/n3',
      'text/turtle'
    ]
```

**Comment by rubensworks** [comment]
That's weird, they should be there, according to our unit tests.
Are you sure you're using the latest version?

Pining @jeswr here as well.

**Comment by BelgianNoise** [comment]
> Are you sure you're using the latest version?

aha, checked the recent PRs and I see that shaclc support was just added.
I still had 2.0.1 cached somewhere and it was using that package for some reason.

Works now, thanks!
